name: poke_scan_tw
description: Traditional Chinese Pokemon Scanner
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 狀態管理
  provider: ^6.1.1
  # 本地儲存
  shared_preferences: ^2.2.2
  # 相機模組
  camera: ^0.10.5+9
  # Google ML Kit (OCR 文字辨識)
  google_mlkit_text_recognition: ^0.11.0
  # 權限管理
  permission_handler: ^11.3.0
  sliver_tools: ^0.2.12
  # Firebase 相關套件
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.0
  google_sign_in: ^6.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/data.json